project:
  type: website
  output-dir: docs

website:
  title: "Franck Deba - Quant"
  site-url: https://usenamefd.github.io/  # Optional but recommended
  navbar:
    background: "white"
    logo: img/logo.svg
    logo-alt: "FDDW Quant Research"  # Important for accessibility
    logo-height: "40px"  # Adjust based on your logo dimensions
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: finance.qmd
        text: Quantitative Finance
      - href: risk-regulation.qmd
        text: Risk & Regulation
      - href: data-science.qmd
        text: Data Science
      - href: articles-ressources.qmd
        text: Resources

    right:
      - icon: linkedin
        href: https://linkedin.com/in/deba-franck
      - icon: github
        href: https://github.com/usernameFD
      - icon: envelope
        href: mailto:debafranck@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2